# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw1i62NDIzrDaTPKXBMOWbepCD8YgJyx
"""

# ─── Global configuration dataclass ─────────────────────────────────────────
from dataclasses import dataclass

@dataclass
class Config:
    # Paths
    DATA_DIR:      str   = './data/aptos2019'
    CSV_TRAIN:     str   = './data/aptos2019/train.csv'
    MODEL_SAVE:    str   = './checkpoints/efficientnet_b4_dr.pth'
    RESULTS_DIR:   str   = './results'

    # Model
    BACKBONE:      str   = 'efficientnet_b4'
    NUM_CLASSES:   int   = 5          # DR grades 0-4
    IMG_SIZE:      int   = 512
    DROPOUT:       float = 0.4

    # Training
    BATCH_SIZE:    int   = 32
    EPOCHS_HEAD:   int   = 5           # Stage 1: head warm-up
    EPOCHS_FULL:   int   = 30          # Stage 2: fine-tune
    LR_HEAD:       float = 1e-3
    LR_FULL:       float = 1e-4
    LR_MIN:        float = 1e-6
    WEIGHT_DECAY:  float = 1e-4
    LABEL_SMOOTH:  float = 0.1
    LAMBDA_KAPPA:  float = 0.3        # weight for kappa loss
    PATIENCE:      int   = 7           # early stopping patience

    # Explanation
    GRADCAM_LAYER: str   = 'blocks.6'  # final MBConv block
    IG_STEPS:      int   = 50
    TOPK_PERCENT:  float = 0.10        # top-10% for AOPC

CFG = Config()
os.makedirs(CFG.RESULTS_DIR, exist_ok=True)
os.makedirs('./checkpoints', exist_ok=True)