# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw1i62NDIzrDaTPKXBMOWbepCD8YgJyx
"""

# ─── DR grading model ────────────────────────────────────────────────────────
class DRClassifier(nn.Module):
    """
    EfficientNet-B4 backbone with a custom classification head
    for 5-class DR severity grading.
    """
    def __init__(self, backbone: str = 'efficientnet_b4',
                 num_classes: int = 5, dropout: float = 0.4):
        super().__init__()
        # Load ImageNet pre-trained backbone via timm
        self.encoder = timm.create_model(
            backbone, pretrained=True, num_classes=0,
            global_pool='avg')          # remove default head
        feat_dim = self.encoder.num_features  # 1792 for B4

        # Custom classification head
        self.head = nn.Sequential(
            nn.Linear(feat_dim, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(512, num_classes)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        features = self.encoder(x)    # (B, 1792)
        return self.head(features)    # (B, 5)

    def freeze_encoder(self):
        """Freeze backbone weights (Stage 1 warm-up)."""
        for param in self.encoder.parameters():
            param.requires_grad = False

    def unfreeze_encoder(self):
        """Unfreeze all weights (Stage 2 fine-tuning)."""
        for param in self.encoder.parameters():
            param.requires_grad = True


def build_model(cfg: Config) -> DRClassifier:
    model = DRClassifier(
        backbone=cfg.BACKBONE,
        num_classes=cfg.NUM_CLASSES,
        dropout=cfg.DROPOUT
    ).to(DEVICE)
    total = sum(p.numel() for p in model.parameters())
    print(f'Parameters: {total/1e6:.2f}M')
    return model