# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw1i62NDIzrDaTPKXBMOWbepCD8YgJyx
"""

# ─── Grad-CAM ────────────────────────────────────────────────────────────────
class GradCAM:
    """
    Gradient-weighted Class Activation Mapping (Selvaraju et al., ICCV 2017).
    Hooks the final MBConv block of EfficientNet-B4.
    """
    def __init__(self, model: nn.Module, target_layer: str):
        self.model        = model
        self.gradients    = None
        self.activations  = None
        self._register_hooks(target_layer)

    def _register_hooks(self, layer_name: str):
        """Attach forward and backward hooks to the target layer."""
        for name, module in self.model.named_modules():
            if name == layer_name:
                module.register_forward_hook(self._save_activation)
                module.register_full_backward_hook(self._save_gradient)
                return
        raise ValueError(f'Layer "{layer_name}" not found in model.')

    def _save_activation(self, module, input, output):
        self.activations = output.detach()   # (B, C, H, W)

    def _save_gradient(self, module, grad_in, grad_out):
        self.gradients = grad_out[0].detach() # (B, C, H, W)

    def generate(self, img_tensor: torch.Tensor,
                 target_class: int = None) -> np.ndarray:
        """
        Compute Grad-CAM heatmap for one image.
        img_tensor : (1, 3, H, W) normalized tensor
        Returns    : heatmap (H, W) in [0, 1]
        """
        self.model.eval()
        img_tensor = img_tensor.to(DEVICE).requires_grad_(True)

        # Forward pass
        output = self.model(img_tensor)         # (1, 5)
        if target_class is None:
            target_class = output.argmax(dim=1).item()

        # Backward pass for target class
        self.model.zero_grad()
        score = output[0, target_class]
        score.backward()

        # alpha_k^c = GAP(gradients)  →  shape (C,)
        weights = self.gradients[0].mean(dim=(1, 2))  # (C,)

        # Weighted sum of activations + ReLU
        cam = (weights[:, None, None] * self.activations[0]).sum(0)
        cam = F.relu(cam)                       # (H', W')

        # Normalize to [0, 1]
        cam = cam.cpu().numpy()
        cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)
        return cam


def overlay_heatmap(img_rgb: np.ndarray,
                     cam: np.ndarray,
                     alpha: float = 0.45) -> np.ndarray:
    """
    Upsample Grad-CAM heatmap and overlay as jet colormap on
    the original RGB fundus image.
    """
    h, w = img_rgb.shape[:2]
    cam_up = cv2.resize(cam, (w, h),
                        interpolation=cv2.INTER_LINEAR)
    heatmap = cv2.applyColorMap(
        (cam_up * 255).astype(np.uint8),
        cv2.COLORMAP_JET)                       # BGR heatmap
    heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
    overlay = (alpha * heatmap +
               (1 - alpha) * img_rgb).astype(np.uint8)
    return overlay


DR_LABELS = {0:'No DR', 1:'Mild NPDR', 2:'Moderate NPDR',
             3:'Severe NPDR', 4:'Proliferative DR'}

def visualize_gradcam(model, img_path: str,
                      cfg: Config, save_path: str = None):
    """
    Full Grad-CAM visualization pipeline for a single fundus image.
    Saves a side-by-side figure: original | Grad-CAM overlay.
    """
    # Load and preprocess
    img_bgr = cv2.imread(img_path)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    img_pre = ben_graham_preprocess(crop_and_resize(img_rgb))

    transform = get_val_transforms(cfg.IMG_SIZE)
    tensor    = transform(image=img_pre)['image'].unsqueeze(0)

    # Grad-CAM
    gcam    = GradCAM(model, cfg.GRADCAM_LAYER)
    cam     = gcam.generate(tensor)
    overlay = overlay_heatmap(img_pre, cam)

    # Predicted grade
    with torch.no_grad():
        logits = model(tensor.to(DEVICE))
        probs  = F.softmax(logits, dim=1)[0].cpu().numpy()
        grade  = probs.argmax()

    # Plot
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    axes[0].imshow(img_pre)
    axes[0].set_title('Original Fundus Image', fontsize=13)
    axes[1].imshow(overlay)
    axes[1].set_title(
        f'Grad-CAM  |  Predicted: {DR_LABELS[grade]}  '
        f'({probs[grade]*100:.1f}%)', fontsize=13)
    for ax in axes:
        ax.axis('off')
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f'Saved: {save_path}')
    plt.show()