# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw1i62NDIzrDaTPKXBMOWbepCD8YgJyx
"""

# ─── Integrated Gradients via Captum ────────────────────────────────────────
def compute_integrated_gradients(model: nn.Module,
                                  img_tensor: torch.Tensor,
                                  target_class: int = None,
                                  steps: int = 50) -> np.ndarray:
    """
    Compute Integrated Gradients attribution map.
    img_tensor : (1, 3, H, W) normalized tensor
    Returns    : attribution map (H, W) in [-1, 1]
    """
    model.eval()
    img_tensor = img_tensor.to(DEVICE)

    if target_class is None:
        with torch.no_grad():
            target_class = model(img_tensor).argmax(dim=1).item()

    ig = IntegratedGradients(model)
    baseline = torch.zeros_like(img_tensor).to(DEVICE)  # black image

    attributions, delta = ig.attribute(
        img_tensor,
        baselines=baseline,
        target=target_class,
        n_steps=steps,
        return_convergence_delta=True)

    # Aggregate across channels: sum of absolute values
    attr = attributions[0].cpu().numpy()         # (3, H, W)
    attr_map = np.abs(attr).sum(axis=0)          # (H, W)
    attr_map = (attr_map - attr_map.min()) / \
               (attr_map.max() - attr_map.min() + 1e-8)

    print(f'IG convergence delta: {delta.item():.6f}')
    return attr_map


# ─── Guided Backpropagation via Captum ───────────────────────────────────────
def compute_guided_gradcam(model: nn.Module,
                            img_tensor: torch.Tensor,
                            gradcam_heatmap: np.ndarray,
                            target_class: int = None) -> np.ndarray:
    """
    Guided Grad-CAM = element-wise(Grad-CAM, GuidedBackprop).
    Returns fine-grained, class-discriminative explanation.
    """
    model.eval()
    img_tensor = img_tensor.to(DEVICE)

    if target_class is None:
        with torch.no_grad():
            target_class = model(img_tensor).argmax(dim=1).item()

    gbp  = GuidedBackprop(model)
    attr = gbp.attribute(img_tensor, target=target_class)
    guided = attr[0].cpu().numpy().transpose(1, 2, 0)  # (H, W, 3)
    guided = np.abs(guided).mean(axis=2)               # (H, W)
    guided = (guided - guided.min()) / \
             (guided.max() - guided.min() + 1e-8)

    # Upsample Grad-CAM to match image resolution
    H, W = guided.shape
    cam_up = cv2.resize(gradcam_heatmap, (W, H),
                        interpolation=cv2.INTER_LINEAR)

    guided_gradcam = guided * cam_up
    guided_gradcam = (guided_gradcam - guided_gradcam.min()) / \
                     (guided_gradcam.max() - guided_gradcam.min() + 1e-8)
    return guided_gradcam