# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw1i62NDIzrDaTPKXBMOWbepCD8YgJyx
"""

# ─── Label-smoothed cross-entropy ───────────────────────────────────────────
class LabelSmoothCE(nn.Module):
    def __init__(self, classes: int = 5, smoothing: float = 0.1):
        super().__init__()
        self.smoothing = smoothing
        self.cls       = classes

    def forward(self, pred: torch.Tensor,
                target: torch.Tensor) -> torch.Tensor:
        confidence = 1.0 - self.smoothing
        smooth_val = self.smoothing / (self.cls - 1)
        one_hot = torch.full_like(pred, smooth_val)
        one_hot.scatter_(1, target.unsqueeze(1), confidence)
        log_prob = F.log_softmax(pred, dim=1)
        return -(one_hot * log_prob).sum(dim=1).mean()


# ─── Differentiable Quadratic Kappa loss ─────────────────────────────────────
class KappaLoss(nn.Module):
    """
    Differentiable approximation of Cohen's quadratic weighted kappa.
    Directly optimizes the primary evaluation metric.
    """
    def __init__(self, num_classes: int = 5):
        super().__init__()
        self.num_classes = num_classes
        # Quadratic weight matrix W[i,j] = (i-j)^2 / (N-1)^2
        idx = torch.arange(num_classes).float()
        W = (idx.unsqueeze(0) - idx.unsqueeze(1)) ** 2
        W /= (num_classes - 1) ** 2
        self.register_buffer('W', W)

    def forward(self, pred: torch.Tensor,
                target: torch.Tensor) -> torch.Tensor:
        prob = F.softmax(pred, dim=1)           # (B, C)
        target_oh = F.one_hot(
            target, self.num_classes).float()   # (B, C)
        # Confusion-like matrix O[i,j] = sum_b p_b[j] * y_b[i]
        O = target_oh.t() @ prob               # (C, C)
        O = O / O.sum()
        # Expected matrix E = outer product of marginals
        hist_pred   = prob.sum(0)              # (C,)
        hist_target = target_oh.sum(0)         # (C,)
        E = torch.outer(hist_target, hist_pred)
        E = E / E.sum()
        num   = (self.W * O).sum()
        denom = (self.W * E).sum()
        return num / (denom + 1e-8)            # 0 = perfect, 1 = worst


# ─── Combined loss ────────────────────────────────────────────────────────────
class CombinedLoss(nn.Module):
    """
    L_total = lambda * L_CE + (1 - lambda) * L_kappa
    lambda defaults to 0.7.
    """
    def __init__(self, cfg: Config):
        super().__init__()
        self.ce    = LabelSmoothCE(cfg.NUM_CLASSES, cfg.LABEL_SMOOTH)
        self.kappa = KappaLoss(cfg.NUM_CLASSES)
        self.lam   = 1.0 - cfg.LAMBDA_KAPPA   # 0.7

    def forward(self, pred, target):
        return self.lam * self.ce(pred, target) + \
               (1 - self.lam) * self.kappa(pred, target)