# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw1i62NDIzrDaTPKXBMOWbepCD8YgJyx
"""

# ─── Main pipeline entry point ───────────────────────────────────────────────
if __name__ == '__main__':

    import argparse
    parser = argparse.ArgumentParser(description='DR Detection Pipeline')
    parser.add_argument('--mode', default='train',
                        choices=['train', 'eval', 'explain'])
    parser.add_argument('--img', default=None,
                        help='Image path for explain mode')
    parser.add_argument('--weights', default=CFG.MODEL_SAVE,
                        help='Path to saved model weights')
    args = parser.parse_args()

    # ── TRAIN MODE ──────────────────────────────────────────────────────────
    if args.mode == 'train':
        print('Starting DR classifier training...')
        model, history = train(CFG)

        # Plot training curves
        plt.figure(figsize=(10, 4))
        plt.subplot(1, 2, 1)
        plt.plot(history['train_qwk'], label='Train QWK')
        plt.plot(history['val_qwk'],   label='Val QWK')
        plt.xlabel('Epoch'); plt.ylabel('QWK')
        plt.title('Quadratic Weighted Kappa'); plt.legend()
        plt.subplot(1, 2, 2)
        plt.plot([a*100 for a in history['val_acc']],
                 color='green', label='Val Accuracy')
        plt.xlabel('Epoch'); plt.ylabel('Accuracy (%)')
        plt.title('Validation Accuracy'); plt.legend()
        plt.tight_layout()
        plt.savefig(f'{CFG.RESULTS_DIR}/training_curves.png', dpi=150)
        plt.show()

    # ── EVAL MODE ───────────────────────────────────────────────────────────
    elif args.mode == 'eval':
        model = build_model(CFG)
        model.load_state_dict(
            torch.load(args.weights, map_location=DEVICE))
        print(f'Loaded weights: {args.weights}')

        _, val_loader = build_loaders(CFG)
        metrics = evaluate(model, val_loader)
        with open(f'{CFG.RESULTS_DIR}/metrics.json', 'w') as f:
            json.dump(metrics, f, indent=2)

    # ── EXPLAIN MODE ─────────────────────────────────────────────────────────
    elif args.mode == 'explain':
        assert args.img, '--img required for explain mode'
        model = build_model(CFG)
        model.load_state_dict(
            torch.load(args.weights, map_location=DEVICE))

        # Load and preprocess
        img_bgr = cv2.imread(args.img)
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_pre = ben_graham_preprocess(crop_and_resize(img_rgb))
        tensor  = get_val_transforms(CFG.IMG_SIZE)(
            image=img_pre)['image'].unsqueeze(0)

        # Grad-CAM
        gcam    = GradCAM(model, CFG.GRADCAM_LAYER)
        cam     = gcam.generate(tensor)

        # Integrated Gradients
        ig_map  = compute_integrated_gradients(
            model, tensor, steps=CFG.IG_STEPS)

        # Guided Grad-CAM
        gg_cam  = compute_guided_gradcam(
            model, tensor, cam)

        # Compute explanation metrics
        aopc    = compute_aopc(model, tensor, cam)
        entropy = map_entropy(cam)
        print(f'AOPC (top 10%): {aopc:.4f}')
        print(f'Map Entropy  : {entropy:.3f} bits')

        # Visualize all three methods side by side
        overlay_gc  = overlay_heatmap(img_pre, cam)
        overlay_ig  = overlay_heatmap(img_pre, ig_map)
        overlay_gg  = overlay_heatmap(img_pre, gg_cam)

        fig, axes = plt.subplots(1, 4, figsize=(20, 5))
        titles    = ['Original', 'Grad-CAM',
                     'Integrated Gradients', 'Guided Grad-CAM']
        images    = [img_pre, overlay_gc, overlay_ig, overlay_gg]
        for ax, title, im in zip(axes, titles, images):
            ax.imshow(im); ax.set_title(title, fontsize=12)
            ax.axis('off')
        plt.suptitle(
            f'Explainability  |  AOPC={aopc:.3f}  '
            f'Entropy={entropy:.2f} bits',
            fontsize=13, fontweight='bold')
        plt.tight_layout()
        out = f'{CFG.RESULTS_DIR}/explanation.png'
        plt.savefig(out, dpi=150, bbox_inches='tight')
        print(f'Explanation figure saved: {out}')
        plt.show()