# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw1i62NDIzrDaTPKXBMOWbepCD8YgJyx
"""

# ─── Ben Graham preprocessing ────────────────────────────────────────────────
def ben_graham_preprocess(img: np.ndarray,
                          sigma: int = 10,
                          alpha: int = 4) -> np.ndarray:
    """
    Subtracts local average using Gaussian blur, amplifying
    high-frequency lesion details (microaneurysms, hemorrhages).
    img  : uint8 RGB image (H x W x 3)
    """
    blurred = cv2.GaussianBlur(img, (0, 0), sigma)
    enhanced = cv2.addWeighted(img, alpha, blurred, -alpha + 1, 128)
    return enhanced


def crop_and_resize(img: np.ndarray, size: int = 512) -> np.ndarray:
    """Remove black borders and resize to (size x size)."""
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    _, thresh = cv2.threshold(gray, 10, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(
        thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if contours:
        x, y, w, h = cv2.boundingRect(
            max(contours, key=cv2.contourArea))
        img = img[y:y+h, x:x+w]
    return cv2.resize(img, (size, size),
                      interpolation=cv2.INTER_LINEAR)


# ─── Augmentation pipelines ──────────────────────────────────────────────────
def get_train_transforms(img_size: int = 512) -> A.Compose:
    return A.Compose([
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.5),
        A.RandomRotate90(p=0.5),
        A.Rotate(limit=30, p=0.6),
        A.ColorJitter(
            brightness=0.2, contrast=0.2,
            saturation=0.1, hue=0.05, p=0.5),
        A.RandomResizedCrop(
            height=img_size, width=img_size,
            scale=(0.8, 1.0), p=0.5),
        A.GaussNoise(var_limit=(0, 0.02 * 255**2), p=0.3),
        A.Resize(img_size, img_size),
        A.Normalize(mean=[0.485, 0.456, 0.406],
                    std=[0.229, 0.224, 0.225]),
        ToTensorV2()
    ])


def get_val_transforms(img_size: int = 512) -> A.Compose:
    return A.Compose([
        A.Resize(img_size, img_size),
        A.Normalize(mean=[0.485, 0.456, 0.406],
                    std=[0.229, 0.224, 0.225]),
        ToTensorV2()
    ])


# ─── Dataset class ───────────────────────────────────────────────────────────
class DRDataset(Dataset):
    """
    Fundus image dataset for DR grading.
    CSV must have columns: 'id_code', 'diagnosis' (0-4).
    """
    def __init__(self, csv_path: str, img_dir: str,
                 transform=None, apply_ben_graham: bool = True):
        self.df          = pd.read_csv(csv_path)
        self.img_dir     = Path(img_dir)
        self.transform   = transform
        self.ben_graham  = apply_ben_graham

    def __len__(self) -> int:
        return len(self.df)

    def __getitem__(self, idx: int):
        row      = self.df.iloc[idx]
        img_path = self.img_dir / f'{row.id_code}.png'
        img = cv2.imread(str(img_path))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Preprocessing
        img = crop_and_resize(img, CFG.IMG_SIZE)
        if self.ben_graham:
            img = ben_graham_preprocess(img)

        if self.transform:
            img = self.transform(image=img)['image']

        label = torch.tensor(int(row.diagnosis), dtype=torch.long)
        return img, label


# ─── Build DataLoaders with oversampling for minority classes ─────────────────
def build_loaders(cfg: Config):
    from sklearn.model_selection import StratifiedShuffleSplit
    from torch.utils.data import WeightedRandomSampler

    df = pd.read_csv(cfg.CSV_TRAIN)
    sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2,
                                 random_state=SEED)
    train_idx, val_idx = next(sss.split(df, df['diagnosis']))

    df_train = df.iloc[train_idx].reset_index(drop=True)
    df_val   = df.iloc[val_idx].reset_index(drop=True)

    # Save split CSVs
    df_train.to_csv('/tmp/train_split.csv', index=False)
    df_val.to_csv('/tmp/val_split.csv',   index=False)

    train_ds = DRDataset('/tmp/train_split.csv', cfg.DATA_DIR,
                          get_train_transforms(cfg.IMG_SIZE))
    val_ds   = DRDataset('/tmp/val_split.csv',   cfg.DATA_DIR,
                          get_val_transforms(cfg.IMG_SIZE))

    # Weighted sampler to oversample minority classes
    class_counts = df_train['diagnosis'].value_counts().sort_index().values
    weights = 1.0 / class_counts[df_train['diagnosis'].values]
    sampler = WeightedRandomSampler(weights, len(weights), replacement=True)

    train_loader = DataLoader(train_ds, batch_size=cfg.BATCH_SIZE,
                              sampler=sampler, num_workers=4,
                              pin_memory=True)
    val_loader   = DataLoader(val_ds, batch_size=cfg.BATCH_SIZE,
                              shuffle=False, num_workers=4,
                              pin_memory=True)
    return train_loader, val_loader