# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw1i62NDIzrDaTPKXBMOWbepCD8YgJyx
"""

# ─── Install dependencies ────────────────────────────────────────────────────
# pip install torch torchvision timm captum albumentations
# pip install scikit-learn matplotlib opencv-python tqdm pandas

import os, cv2, json, time, math, random
import numpy as np
import pandas as pd
from pathlib import Path
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.cuda.amp import GradScaler, autocast
import timm                          # EfficientNet-B4 backbone
import albumentations as A           # image augmentation
from albumentations.pytorch import ToTensorV2
from sklearn.metrics import (cohen_kappa_score, accuracy_score,
                             roc_auc_score, classification_report)
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from captum.attr import IntegratedGradients, GuidedBackprop

# ─── Reproducibility ─────────────────────────────────────────────────────────
SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
torch.backends.cudnn.deterministic = True

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {DEVICE}')