# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw1i62NDIzrDaTPKXBMOWbepCD8YgJyx
"""

# ─── One epoch of training ───────────────────────────────────────────────────
def train_epoch(model, loader, optimizer,
                criterion, scaler) -> dict:
    model.train()
    total_loss = 0.0
    all_preds, all_labels = [], []

    for imgs, labels in loader:
        imgs   = imgs.to(DEVICE, non_blocking=True)
        labels = labels.to(DEVICE, non_blocking=True)

        optimizer.zero_grad()
        with autocast():                  # mixed precision
            logits = model(imgs)
            loss   = criterion(logits, labels)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        scaler.step(optimizer)
        scaler.update()

        total_loss += loss.item() * imgs.size(0)
        preds = logits.argmax(dim=1).cpu().numpy()
        all_preds.extend(preds)
        all_labels.extend(labels.cpu().numpy())

    qwk = cohen_kappa_score(all_labels, all_preds,
                             weights='quadratic')
    return {'loss': total_loss / len(loader.dataset),
            'qwk':  qwk}


# ─── Validation epoch ────────────────────────────────────────────────────────
@torch.no_grad()
def val_epoch(model, loader, criterion) -> dict:
    model.eval()
    total_loss = 0.0
    all_preds, all_labels, all_probs = [], [], []

    for imgs, labels in loader:
        imgs   = imgs.to(DEVICE)
        labels = labels.to(DEVICE)
        with autocast():
            logits = model(imgs)
            loss   = criterion(logits, labels)
        probs = F.softmax(logits, dim=1).cpu().numpy()
        preds = logits.argmax(dim=1).cpu().numpy()
        total_loss   += loss.item() * imgs.size(0)
        all_probs.extend(probs)
        all_preds.extend(preds)
        all_labels.extend(labels.cpu().numpy())

    all_probs  = np.array(all_probs)
    all_labels = np.array(all_labels)
    all_preds  = np.array(all_preds)
    qwk  = cohen_kappa_score(all_labels, all_preds,
                              weights='quadratic')
    acc  = accuracy_score(all_labels, all_preds)
    # One-vs-rest AUC
    auc  = roc_auc_score(
        all_labels, all_probs,
        multi_class='ovr', average='macro')
    return {'loss': total_loss / len(loader.dataset),
            'qwk': qwk, 'acc': acc, 'auc': auc}


# ─── Full two-stage training routine ─────────────────────────────────────────
def train(cfg: Config):
    train_loader, val_loader = build_loaders(cfg)
    model     = build_model(cfg)
    criterion = CombinedLoss(cfg).to(DEVICE)
    scaler    = GradScaler()
    history   = {'train_qwk': [], 'val_qwk': [], 'val_acc': []
                 }

    # ── Stage 1: Head warm-up ────────────────────────────────────────────────
    print('\n=== Stage 1: Head Warm-up ===')
    model.freeze_encoder()
    optimizer = torch.optim.Adam(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=cfg.LR_HEAD, weight_decay=cfg.WEIGHT_DECAY)

    for epoch in range(cfg.EPOCHS_HEAD):
        tr = train_epoch(model, train_loader, optimizer,
                         criterion, scaler)
        vl = val_epoch(model, val_loader, criterion)
        print(f'Ep {epoch+1:02d} | '
              f'Loss {tr["loss"]:.4f} | '
              f'Val QWK {vl["qwk"]:.4f} | '
              f'Val Acc {vl["acc"]*100:.2f}%')

    # ── Stage 2: Full fine-tuning ─────────────────────────────────────────────
    print('\n=== Stage 2: Full Fine-Tuning ===')
    model.unfreeze_encoder()
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=cfg.LR_FULL, weight_decay=cfg.WEIGHT_DECAY)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=cfg.EPOCHS_FULL,
        eta_min=cfg.LR_MIN)

    best_qwk = 0.0
    patience_counter = 0

    for epoch in range(cfg.EPOCHS_FULL):
        tr = train_epoch(model, train_loader, optimizer,
                         criterion, scaler)
        vl = val_epoch(model, val_loader, criterion)
        scheduler.step()

        history['train_qwk'].append(tr['qwk'])
        history['val_qwk'].append(vl['qwk'])
        history['val_acc'].append(vl['acc'])

        print(f'Ep {epoch+1:02d} | Loss {tr["loss"]:.4f} | '
              f'QWK {vl["qwk"]:.4f} | '
              f'AUC {vl["auc"]:.4f} | '
              f'Acc {vl["acc"]*100:.2f}%')

        # Save best checkpoint
        if vl['qwk'] > best_qwk:
            best_qwk = vl['qwk']
            torch.save(model.state_dict(), cfg.MODEL_SAVE)
            print(f'  >> Saved best model (QWK={best_qwk:.4f})')
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= cfg.PATIENCE:
                print('Early stopping triggered.')
                break

    print(f'\nBest Validation QWK: {best_qwk:.4f}')
    return model, history